### ISSUE TITLE
分辨率能否提高

### ISSUE THREAD

**Issue by imldy** [hellodk34/avatars#1]
目前的看缩略图还可以，点开就没法看了。

**Comment by hellodk34** [comment]
@imldy 已提交 https://github.com/hellodk34/avatars/releases/tag/v1.0.2 
可以重新阅读一下  readme 增加的参数是 `PIXEL` ，执行时后面加个 1 到 2048 之间的数字即可下载对应分辨率的正方形头像。

![1.png](https://raw.githubusercontent.com/hellodk34/avatars/main/screenshots/1.png)
